// <auto-generated />
namespace DesafioLanche.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class descricao_promocao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(descricao_promocao));
        
        string IMigrationMetadata.Id
        {
            get { return "202010032105014_descricao_promocao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
